kind: Deployment
apiVersion: apps/v1
metadata:
name: healthcare
spec:
replicas: 1
selector:
matchLabels:
name: healthcare
template:
metadata:
name: testp1
labels:
name: healthcare
spec:
containers:
- name: simple-container
image: rajatk2611/healthcare-rajat:26
ports:
- containerPort: 8082
---
kind: Service
apiVersion: v1
metadata:
name: healthcare
spec:
ports:
- port: 80
targetPort: 8082
nodePort: 30007
selector:
name: healthcare
type: NodePort
